### ISSUE TITLE
Refine use cases and requirements for realtime_support

### ISSUE THREAD

**Issue by tfoote** [ros2/realtime_support#17]
Such as do we need multi-threading in realtime etc.

**Comment by jacquelinekay** [comment]
initial brainstorm (to be distilled into a document later, feel free to discuss now):

- multithreading tends to be platform/os-specific
- therefore, threading/synchronization primitives should be modular in rclcpp

hard real time
- hardware multithreading is allowable--RT tasks should be separated into a hardware thread on the appropriate processor (http://www.ecnmag.com/article/2012/05/real-time-apps-using-multi-threads). but sharing a software RT thread and non-RT thread on same processor unallowable
- frameworks/OS's such as Xenomai offer APIs for threading https://xenomai.org/2014/06/xenomai-white-paper/#Multi-threading

soft real time
- software threads allowable, need high priority

embedded
- what we consider "small" embedded systems probably will not have multiple cores so we're not worrying about concurrency on those platforms right now (right @codebot?)

- systems with multiple cores but somewhat limited resources and possible real-time, e.g. robot using a "large" x86 board or ARM smartphone-like board
- desktop applications with (soft) real-time constraints, e.g. control software or video streaming visualization applications

questions
- will atomics work on our target architectures? probably
- how to refactor rclcpp so that global interrupt condition mutex, condition variable are modular? maybe extended from Context?
- consider implementing a PthreadExecutor and XenomaiExecutor (as well as PThreadContext and XenomaiContext if we go that way?)
- where does DDS waiting fit in?

**Comment by jacquelinekay** [comment]
Closed by #73
